name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo  "$VERCEL_ORG_ID ${{ secrets.VERCEL_ORG_ID }}"
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=IKvAcDu1lZbWA6HqFCPg1Dvp
      - name: Build Project Artifacts
        run: vercel build --prod --token=IKvAcDu1lZbWA6HqFCPg1Dvp
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=IKvAcDu1lZbWA6HqFCPg1Dvp
